name: Hourly Weather Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    # ADD THIS PERMISSIONS BLOCK
    permissions:
      contents: write # This gives the job permission to push to the repository

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the data pipeline script
        run: python pipeline.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather_data.db weather_data.csv
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit. Data is up-to-date."
          else
            git commit -m "Automated weather data update"
            git push
          fi